-- Artículos y productos (diseño 01). Lo común de todo lo que se vende en caja va en `articulos`;
-- lo propio de lo físico, en `productos`. Los servicios y los kits (diseño 03) llegan después.
-- Ids nuevos con UUID v7 (docs/decisiones/2026-10-01-uuid-v7.md); los migrados de la v1 conservan el suyo.

CREATE TABLE articulos (
    id                   uuid          PRIMARY KEY DEFAULT uuidv7(),
    nid                  integer       NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY CHECK (nid > 0),
    kind                 text          NOT NULL CHECK (kind IN ('producto', 'servicio', 'kit')),
    nombre               text          NOT NULL CHECK (btrim(nombre) <> '' AND char_length(nombre) <= 150),
    categoria_id         uuid          NOT NULL REFERENCES categorias,
    unidad_medida_id     uuid          NOT NULL REFERENCES unidades_medida,
    precio_venta         numeric(12,2) CHECK (precio_venta > 0),
    descripcion          text          CHECK (btrim(descripcion) <> ''),
    descontinuado_at     timestamptz,
    motivo_descontinuado text          CHECK (btrim(motivo_descontinuado) <> ''),
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    updated_by           uuid          REFERENCES usuarios,
    -- Descontinuar siempre lleva su motivo, y el motivo solo existe si se descontinuó.
    CONSTRAINT articulos_descontinuado_con_motivo
        CHECK ((descontinuado_at IS NULL) = (motivo_descontinuado IS NULL)),
    -- Para que `productos` (y después `servicios`) solo apunten a un artículo de su tipo.
    CONSTRAINT articulos_id_kind_unique UNIQUE (id, kind)
);

-- Sin UNIQUE en el nombre: la v1 tiene 38 nombres repetidos, y los duplicados se corrigen
-- fusionando (diseño 02), no con un choque al guardar.
CREATE INDEX articulos_categoria ON articulos (categoria_id);

COMMENT ON TABLE articulos IS
    'Todo lo que se vende en caja: un producto, un servicio o un kit. Se descontinúa, no se borra.';
COMMENT ON COLUMN articulos.nid IS
    'Número corto para teclearlo en caja y para la etiqueta. Consecutivo; los de la v1 se conservan al migrar.';
COMMENT ON COLUMN articulos.kind IS
    'producto (lleva stock; su renglón en productos), servicio o kit (diseño 03).';
COMMENT ON COLUMN articulos.unidad_medida_id IS
    'En un producto, su unidad base: en ella se cuentan el stock y el costo. En un servicio, en qué se cobra.';
COMMENT ON COLUMN articulos.precio_venta IS
    'Precio actual de una unidad. NULL = no tiene precio fijo: un producto por llegar, un kit o un servicio de precio libre.';
COMMENT ON COLUMN articulos.descontinuado_at IS
    'Desde cuándo ya no se maneja. NULL = se sigue manejando. Conserva su historia.';
COMMENT ON COLUMN articulos.motivo_descontinuado IS
    'Por qué ya no se maneja ("el proveedor ya no lo vende"). Obligatorio al descontinuar.';
COMMENT ON COLUMN articulos.updated_by IS
    'Quién lo cambió por última vez. NULL = migrado de la v1.';

CREATE TABLE productos (
    articulo_id uuid PRIMARY KEY,
    kind        text NOT NULL DEFAULT 'producto' CHECK (kind = 'producto'),
    marca       text CHECK (btrim(marca) <> ''),
    modelo      text CHECK (btrim(modelo) <> ''),
    color       text CHECK (btrim(color) <> ''),
    FOREIGN KEY (articulo_id, kind) REFERENCES articulos (id, kind)
);

COMMENT ON TABLE productos IS
    'Lo propio de un artículo físico: se compra, lleva stock y se revende o se consume en un servicio.';
COMMENT ON COLUMN productos.kind IS
    'Siempre producto: junto con articulo_id impide que un servicio o un kit tenga renglón aquí.';

CREATE TABLE precios_historial (
    id           uuid          PRIMARY KEY DEFAULT uuidv7(),
    articulo_id  uuid          NOT NULL REFERENCES articulos,
    precio_venta numeric(12,2) NOT NULL CHECK (precio_venta > 0),
    desde        timestamptz   NOT NULL DEFAULT now(),
    updated_by   uuid          REFERENCES usuarios
);
CREATE INDEX precios_historial_articulo_desde ON precios_historial (articulo_id, desde);

COMMENT ON TABLE precios_historial IS
    'Cada precio de venta que ha tenido un artículo. Se escribe al cambiarlo; sirve para reportes (la venta guarda el precio cobrado).';
COMMENT ON COLUMN precios_historial.updated_by IS
    'Quién puso el precio. NULL = migrado de la v1.';

-- Los ids nuevos de las tablas que ya existían también son UUID v7. Los ya creados se quedan.
ALTER TABLE categorias      ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE unidades_medida ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE roles           ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE usuarios        ALTER COLUMN id SET DEFAULT uuidv7();
