[package]
name = "privada"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kernel.workspace = true
inventario.workspace = true
usuarios.workspace = true
negocio-config.workspace = true
db.workspace = true
serde.workspace = true
askama.workspace = true
rpassword.workspace = true
tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
http-body-util.workspace = true
serde_json.workspace = true
sqlx.workspace = true
usuarios = { workspace = true, features = ["pruebas"] }

[lints]
workspace = true
