[package]
name = "db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kernel.workspace = true
inventario.workspace = true
usuarios.workspace = true
sqlx.workspace = true

[dev-dependencies]
tokio.workspace = true
inventario = { workspace = true, features = ["test-support"] }
usuarios = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
